Musica musica1 = new Musica();
Musica musica2 = new Musica();
musica1.nome = "Roxane";
musica1.artista = "The Police";
musica1.duracao = 273;
musica1.disponivel = true;
musica1.ExibirFichaTecnica();
Console.WriteLine();
musica2.nome = "Vertigo";
musica2.artista = "U2";
musica2.duracao = 367;
musica2.disponivel = false;
musica2.ExibirFichaTecnica();